spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
  batch:
    job:
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: embedded
      #?? DB? ?? ??

---
spring:
  config:
    activate:
      on-profile: mysql
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/springbatch?useUnicoe=true&characterEncoding=utf8
      username: study
      password: 1234
      driver-class-name: com.mysql.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always
      #Never? ??? Batch??? ??? job??? ?? ??!
    job:
#      enabled: false

      # ?? ?? ?? ?? default? true
      names: ${job.name:NONE}
